### ISSUE TITLE
Update external dependencies

### ISSUE THREAD

**Issue by Dignifiedquire** [karma-runner/karma#1410]
- [x] `http-proxy           0.10.4  -> 1.11.1` Ref #1345
- [x] `rimraf                2.2.8  -> 2.3.3` Ref #1412
- [x] `glob                 3.2.11  -> 5.0.6` Ref #1412
- [x] `colors                0.6.2  -> 1.1.0` Ref #1412
- [x] `mime                 1.2.11  -> 1.3.4` Ref #1412
- [x] `graceful-fs           2.0.3  -> 3.0.6` Ref #1412
- [x] `useragent            2.0.10  -> 2.1.6` Ref #1412
- [x] `connect              2.26.6  -> 3.3.5` Ref #1413
- [x] `lodash                2.4.2  -> 3.8.0` Ref #1412
- [x] `minimatch            0.2.14  -> 2.0.7` Ref #1412
- [x] `source-map           0.1.43  -> 0.4.2` Ref #1412

---

Superseds #1163, #1327
